server:
  port: 8084
spring:
  application:
    name: simple-coupon-system-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8081/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug
