server:
  port: 7001
  servlet:
    context-path: /coupon-template

spring:
  application:
    name: simple-coupon-system-template
  jpa:
    show-sql: true
    #配置 hibernate.dialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    # 数据源
    url: jdbc:mysql://127.0.0.1:3306/simple_coupon_data?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    # 连接池
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: ImoocCouponHikariCP
  redis:
    database: 0
    host: 192.168.1.5
    port: 6379
    password: root
    # 连接超时时间
    timeout: 10000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8081/eureka/

# ------------------------------------------------------------------------------------------------------

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: simple-coupon-system-template
    groupId: com.coupon.system.template
    artifactId: simple-coupon-system-template
    version: 1.0-SNAPSHOT

# ------------------------------------------------------------------------------------------------------

logging:
  level:
    com.coupon.system: debug
